import type { Recipe } from "@/types";

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Classic Tomato Bruschetta",
    description: "A timeless Italian appetizer featuring fresh tomatoes, basil, garlic, and olive oil on toasted bread.",
    imageUrl: "https://placehold.co/600x400.png",
    cookTime: "15 min",
    servings: "4",
    rating: 4.8,
    author: "Chef Isabella",
    ingredients: [
      { name: "Baguette", quantity: "1" },
      { name: "Ripe tomatoes, diced", quantity: "4" },
      { name: "Garlic cloves, minced", quantity: "2" },
      { name: "Fresh basil, chopped", quantity: "1/4 cup" },
      { name: "Extra virgin olive oil", quantity: "2 tbsp" },
      { name: "Balsamic glaze", quantity: "for drizzling" },
      { name: "Salt and pepper", quantity: "to taste" },
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Slice the baguette into 1/2-inch thick slices. Arrange on a baking sheet and toast for 5-7 minutes, or until golden.",
      "In a bowl, combine diced tomatoes, minced garlic, chopped basil, and olive oil. Season with salt and pepper.",
      "Rub one side of each toasted bread slice with a garlic clove.",
      "Top each slice with the tomato mixture.",
      "Drizzle with balsamic glaze before serving.",
    ],
    nutrition: {
      calories: "150 kcal",
      protein: "4g",
      carbs: "20g",
      fat: "6g",
    },
  },
  {
    id: "2",
    title: "Spicy Thai Green Curry",
    description: "A fragrant and flavorful Thai green curry with chicken and vegetables, perfect for a weeknight meal.",
    imageUrl: "https://placehold.co/600x400.png",
    cookTime: "30 min",
    servings: "4",
    rating: 4.9,
    author: "Chef Kenji",
    ingredients: [
      { name: "Chicken breast, sliced", quantity: "1 lb" },
      { name: "Coconut milk", quantity: "1 can (13.5 oz)" },
      { name: "Green curry paste", quantity: "3 tbsp" },
      { name: "Bamboo shoots, sliced", quantity: "1 cup" },
      { name: "Bell pepper, sliced", quantity: "1" },
      { name: "Thai basil leaves", quantity: "1/2 cup" },
      { name: "Fish sauce", quantity: "2 tsp" },
      { name: "Sugar", quantity: "1 tsp" },
    ],
    instructions: [
      "In a large pot or wok, heat 1/4 cup of coconut milk over medium heat until it starts to bubble.",
      "Add the green curry paste and cook for 1 minute until fragrant.",
      "Add the chicken and cook until no longer pink.",
      "Stir in the remaining coconut milk, fish sauce, and sugar. Bring to a simmer.",
      "Add the bamboo shoots and bell pepper. Cook for 5-7 minutes until vegetables are tender-crisp.",
      "Remove from heat and stir in the Thai basil leaves.",
      "Serve hot with jasmine rice.",
    ],
    nutrition: {
      calories: "450 kcal",
      protein: "35g",
      carbs: "15g",
      fat: "28g",
    },
  },
  {
    id: "3",
    title: "Hearty Lentil Soup",
    description: "A nourishing and comforting vegetarian lentil soup packed with vegetables and flavor.",
    imageUrl: "https://placehold.co/600x400.png",
    cookTime: "45 min",
    servings: "6",
    rating: 4.7,
    author: "Healthy Eats",
    ingredients: [
      { name: "Brown lentils, rinsed", quantity: "1 cup" },
      { name: "Vegetable broth", quantity: "6 cups" },
      { name: "Onion, chopped", quantity: "1" },
      { name: "Carrots, chopped", quantity: "2" },
      { name: "Celery stalks, chopped", quantity: "2" },
      { name: "Diced tomatoes, canned", quantity: "1 (14.5 oz)" },
      { name: "Cumin", quantity: "1 tsp" },
      { name: "Thyme", quantity: "1/2 tsp" },
      { name: "Spinach", quantity: "2 cups" },
    ],
    instructions: [
      "In a large pot, heat olive oil over medium heat. Sauté onion, carrots, and celery until softened (about 5-7 minutes).",
      "Add garlic and cook for another minute.",
      "Stir in the vegetable broth, lentils, diced tomatoes, cumin, and thyme. Bring to a boil.",
      "Reduce heat, cover, and simmer for 30-40 minutes, or until lentils are tender.",
      "Stir in spinach and cook until wilted.",
      "Season with salt and pepper to taste. Serve hot.",
    ],
    nutrition: {
      calories: "250 kcal",
      protein: "15g",
      carbs: "45g",
      fat: "2g",
    },
  },
  {
    id: "4",
    title: "Lemon Herb Baked Salmon",
    description: "A simple yet elegant baked salmon recipe with fresh lemon and herbs. Quick, healthy, and delicious.",
    imageUrl: "https://placehold.co/600x400.png",
    cookTime: "20 min",
    servings: "2",
    rating: 4.9,
    author: "Quick Meals",
    ingredients: [
      { name: "Salmon fillets", quantity: "2 (6 oz each)" },
      { name: "Lemon, sliced", quantity: "1" },
      { name: "Fresh dill, chopped", quantity: "2 tbsp" },
      { name: "Fresh parsley, chopped", quantity: "2 tbsp" },
      { name: "Olive oil", quantity: "1 tbsp" },
      { name: "Salt and pepper", quantity: "to taste" },
    ],
    instructions: [
      "Preheat oven to 400°F (200°C).",
      "Place salmon fillets on a parchment-lined baking sheet.",
      "Drizzle with olive oil and season with salt and pepper.",
      "In a small bowl, mix together dill and parsley. Sprinkle over the salmon.",
      "Top each fillet with lemon slices.",
      "Bake for 12-15 minutes, or until salmon is cooked through and flakes easily.",
      "Serve immediately with your favorite side.",
    ],
    nutrition: {
      calories: "350 kcal",
      protein: "40g",
      carbs: "2g",
      fat: "20g",
    },
  },
];
